# 服务器配置
server:
  port: 8080
  mode: "debug" # debug, release, test
  read_timeout: 60
  write_timeout: 60

# 数据库配置
mysql:
  host: "127.0.0.1"
  port: 3306
  username: "root"
  password: "root"
  database: "gochat_im"
  max_idle_conns: 10
  max_open_conns: 100
  conn_max_lifetime: 3600 # 单位：秒

# Redis配置
redis:
  host: "127.0.0.1"
  port: 6379
  password: "root"
  db: 0
  pool_size: 100
  min_idle_conns: 10
  dial_timeout: 5 # 单位：秒
  read_timeout: 3 # 单位：秒
  write_timeout: 3 # 单位：秒

# Kafka配置
kafka:
  brokers: ["localhost:9092"]
  topic: "gochat_messages"
  consumer_group: "gochat_consumer"
  producer:
    return_success: true
    return_errors: true
    timeout: 10 # 单位：秒
  consumer:
    offset_initial: -1 # -1: newest, -2: oldest
    fetch_min: 1
    fetch_default: 1024 * 1024 # 1MB

# JWT配置
jwt:
  secret_key: "ooqz0nO9ZfIlQzWSkpEHhX9B+PetgKnDE5nLR7H0FWQ="
  expires_time: 1800 # 单位：秒，7天
  refresh_expires_time: 86400
  issuer: "GochatIM"
  buffer_time: 300 # 单位：秒，1天，缓冲时间用于提前刷新token

# Nginx配置（用于反向代理和静态资源）
nginx:
  static_path: "/static"
  upload_path: "/uploads"
  max_file_size: 50 # 单位：MB

# 日志配置
log:
  level: "info" # debug, info, warn, error
  format: "json" # json, text
  output: "file" # console, file
  file_path: "logs/gochat.log"
  max_size: 100 # 单位：MB
  max_age: 30 # 单位：天
  max_backups: 10
  compress: true

# 消息配置
message:
  max_length: 4096
  history_count: 100
  cache_time: 3600 # 单位：秒

# 用户配置
user:
  avatar_path: "uploads/avatars"
  default_avatar: "default.png"
  password_hash_cost: 10